comments/urls.py
from django.urls import path
from comments import views

app_name = 'comments'

urlpatterns = [
    path('', views.CommentListView.as_view(), name='comment_list'),
    path('create/<slug:slug>', views.CommentCreateView.as_view(), name='comment_create'),
    # path('detail/<slug:slug>', views.PostDetailView.as_view(), name='post_detail'),
    path('update/<slug:slug>', views.CommentUpdateView.as_view(), name='comment_update'),
    path('delete/<slug:slug>', views.CommentDeleteView.as_view(), name='comment_delete'),
]

customBlog/urls.py
from django.contrib import admin
from django.urls import path, include
from customBlog import views, settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexTemplateView.as_view(), name='index'),
    path('about', views.AboutTemplateView.as_view(), name='about'),
    path('contact', views.ContactTemplateView.as_view(), name='contact'),
    path('posts/', include('posts.urls', namespace='posts')),
    path('comments/', include('comments.urls', namespace='comments')),
    path('comments_api/', include('comments.api.urls', namespace='comments_api')),
    path('profiles/', include('profiles.urls', namespace='profiles')),


    path('accounts/', include('allauth.urls')),

    path('ckeditor/', include('ckeditor_uploader.urls')),

]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from posts import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostListView.as_view(), name='post_list'),
    path('create', views.PostCreateView.as_view(), name='post_create'),
    path('detail/<slug:slug>', views.PostDetailView.as_view(), name='post_detail'),
    path('update/<slug:slug>', views.PostUpdateView.as_view(), name='post_update'),
    path('delete/<slug:slug>', views.PostDeleteView.as_view(), name='post_delete'),
    path('search', views.post_search, name='post_search'),
]

posts/models.py
from django.shortcuts import reverse
from django.db import models
from django.contrib.auth import get_user_model
from django.db.models.signals import pre_save

from django.db.models.signals import pre_save

from django.utils.text import slugify

from posts.utils import unique_slug

from ckeditor_uploader.fields import RichTextUploadingField

User = get_user_model()


# Create your models here.
class Post(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	title = models.CharField(max_length=100)
	message = models.TextField()
	body = RichTextUploadingField(null=True, blank=True)

	# auto_now_add - When the post was created - CREATED
	created = models.DateTimeField(auto_now_add=True)

	# auto_now - every time you update the post, UPDATE
	updated = models.DateTimeField(auto_now=True)

	# Slug Field
	slug = models.SlugField(unique=True)


	def __str__(self):
		return f'{self.title}'
	

	def get_absolute_url(self, **kwargs):
		# Original method to call a item
		# return reverse('posts:post_detail', kwargs={'pk':self.pk})

		# This is how to call an item by it's Slug value
		return reverse('posts:post_detail', kwargs={'slug':self.slug})

# Before saving the data I want to add the SlugField automatically
# Pre_save method can help us here
def pre_save_add_slug(sender, instance, *args, **kwargs):
	# print(sender)
	# print(instance, instance.title, instance.message, instance.created)
	# print(args)
	# print(kwargs)

	if not instance.slug:
		# instance.slug = slugify(instance.title)
		instance.slug = unique_slug(instance)

# @receiver(pre_save) is the same as doing the below operation

pre_save.connect(pre_save_add_slug, sender=Post)

posts/forms.py
from django import forms
from posts.models import Post

class PostForm(forms.ModelForm):
	class Meta:
		model = Post
		fields = ['title', 'message', 'body']
		widgets = {
			'title': forms.TextInput(attrs={'class':'form-control'}),
			'message': forms.Textarea(attrs={'class':'form-control'}),
		}

posts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy

# Create your views here.
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from posts.models import Post
from posts.forms import PostForm
from posts.mixins import PostOwnerMixin

from comments.models import Comment

class PostListView(ListView):
	model = Post

class PostDetailView(DetailView):
	model = Post


	def get_context_data(self, *args, **kwargs):
		context = super().get_context_data(*args, **kwargs)

		# post = Post.objects.get(pk=11)
		# print('\nCurrent Post',post, '\n')

		# print(dir(post))
		# print(dir(post.comment_set))
		# print(post.comment_set.all())
		# print(post.comments.all())

		# print('This is my Post', context['post'])

		# context['approved_comments'] = Comment.objects.filter(post=context['post'].id, approval_status=True)
		context['approved_comments'] = Comment.objects.approved(context['post'].id)
		return context




class PostCreateView(LoginRequiredMixin, CreateView):
	model = Post
	form_class = PostForm

	def form_valid(self, form, *args, **kwargs):
		# print(form)
		# print(self)
		# print(args)
		# print(kwargs)
		post = form.save(commit=False)

		# print(self.request.user)
		# print(post.title, post.message)

		post.user = self.request.user
		post.save()
		return super().form_valid(form)

class PostUpdateView(PostOwnerMixin, UpdateView):
	model = Post
	form_class = PostForm

class PostDeleteView(PostOwnerMixin, DeleteView):
	model = Post
	success_url = reverse_lazy('posts:post_list')



def post_search(request):
	query = request.GET.get('query', None)
	# print('Query from Search:', query)
	post_list = []

	if query is not None:
		post_list = Post.objects.filter(title__icontains=query)

	context = {
		'post_list': post_list,
		'query': query,
	}


	return render(request, 'posts/post_list.html', context)
	
	

posts/templates/posts/post_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<h1>Post Delete</h1>

<form method='POST'>
	{% csrf_token %}
	Would you like to delete {{post}}?
	<input class='btn btn-danger' type="submit" value="Delete">
</form>

{% endblock %}

posts/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1>Post Detail</h1>

<div class="card">
	<div class="card-header">
		<p>{{post.id}}. {{post.title}}</p>
		<p>{{post.user}}</p>
	</div>
	<div class="card-body">
		<p>{{post.message}}</p>
		<p>{{post.body | safe }}</p>
		<p>Post Created: {{post.created}}</p>
		<p>Last Updated: {{post.updated}}</p>
	</div>
</div>

<p>Post Author {{post.user}}</p>

<p>User Logged In {{user}}</p>

{% if post.user == user %}
	<a class='btn btn-info mt-4' href="{% url 'posts:post_update' slug=post.slug %}">Update</a>

	<a class='btn btn-danger mt-4 ms-4' href="{% url 'posts:post_delete' slug=post.slug %}">Delete</a>
{% endif %}
<hr>
<a href="{% url 'comments:comment_create' slug=post.slug %}">Add a Comment</a>
<hr>
<h4>Comments</h4>


{% for comment in approved_comments %}
	<div class="card">
		<div class="card-header">
			<div class="row">
				

				<div class="col-9">
					<p>{{comment.post}}</p>	
					<p>Written By: {{comment.user}}</p>	
				</div>
				
			</div>
			
		</div>
		<div class="card-body">
			<p>{{comment.message}}</p>
			{% if comment.user == user %}
				<a class='btn btn-info' href="{% url 'comments:comment_update' slug=comment.slug %}">Update</a>
				<a class='btn btn-danger' href="{% url 'comments:comment_delete' slug=comment.slug %}">Delete</a>
			{% elif post.user == user %}
				<a class='btn btn-danger' href="{% url 'comments:comment_delete' slug=comment.slug %}">Delete</a>

			{% endif %}
		</div>
	</div>


{% endfor %}



























<script src="{% static 'js/main.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/js-cookie@rc/dist/js.cookie.min.js"></script>


{% endblock %}

posts/templates/posts/post_form.html
{% extends 'base.html' %}

{% block content %}
<h1>Post Create or Update</h1>

<form method='POST'>
	{% csrf_token %}
	{{form.media}}
	{{form.as_p}}
	<input class='btn btn-info' type="submit" value="Create">
</form>


{% endblock %}

posts/templates/posts/post_list.html
{% extends 'base.html' %}

{% block content %}
<h1>Post List</h1>

<hr>
<a class='btn btn-primary' href="{% url 'posts:post_create' %}">Add a Post</a>
<hr>

{% if query %}
	<h3>Here are the results of your search for: <span class='text-success'>{{query}}</span></h3>
{% endif %}

{% for post in post_list %}
	<div class="card mt-5">
		<div class="card-header">
			<p><a href="{% url 'posts:post_detail' slug=post.slug %}"> {{post.id}}. {{post.title}}</a></p>
			<p>Author {{post.user}}</p>
		</div>
		<div class="card-body">
			<p>{{post.message}}</p>
			<p>Post Created: {{post.created}}</p>
			<p>Last Updated: {{post.updated}}</p>
		</div>
	</div>
{% endfor %}

{% endblock %}